[default]
src = 'test/solidity'
out = 'artifacts/foundry'
cache_path = 'cache/foundry'
fuzz_runs = 6_666
verbosity = 3

[production]
src = 'test/solidity'
out = 'artifacts/foundry'
fuzz_runs = 66_666
