[profile.default]
solc = '0.8.15'
optimizer = true
optimizer_runs = 200

ffi = true
src = 'test/solidity'
out = 'artifacts/.foundry'
cache_path = 'cache/.foundry'
fuzz_runs = 6_666
verbosity = 3

[profile.production]
fuzz_runs = 6 # // TODO 66_666

[profile.snapshot]
fuzz_runs = 666

[profile.development]
fuzz_runs = 666
verbosity = 5
